import { Clock3, Mail, MapPin, MessageCircleMore, Phone } from "lucide-react"
import { SiteFooter, SiteHeader } from "@/components/site-shell"

export default function Contact() {
  return <><SiteHeader /><main>
    <div className="sub-hero contact-subhero"><div className="site-container subhero-layout"><div className="subhero-copy"><span className="kicker">CONTACT & CONSULTING</span><h1>세무 상담 문의</h1><p>간단한 사업 상황을 알려주시면 상담 가능한 범위와 미리 준비할 자료를 친절하게 안내드립니다.</p><div className="subhero-chips"><span>02-553-1159</span><span>선릉역 인근</span></div></div><div className="contact-title-visual"><div className="contact-bubble"><MessageCircleMore /><span><small>편안한 첫 상담</small><strong>무엇부터 물어봐야 할지<br />몰라도 괜찮습니다</strong></span></div><div className="contact-quick"><span><Phone /><small>전화상담</small></span><span><Mail /><small>이메일</small></span><span><Clock3 /><small>일정확인</small></span></div></div></div></div>
    <section className="section"><div className="site-container contact-grid"><div className="contact-info"><h2>상담 안내</h2><p>상담 전 현재 사업 단계와 궁금한 내용을 알려주시면 더 정확한 안내가 가능합니다.</p><div><Phone /><span><small>전화 · 팩스</small><a href="tel:025531159">02-553-1159</a> · F. 02-553-1160</span></div><div><Mail /><span><small>이메일</small><a href="mailto:daewontax01@gmail.com">daewontax01@gmail.com</a></span></div><div><MapPin /><span><small>주소</small>서울 강남구 테헤란로 313, 205호<br />(역삼동, 성지하이츠1)</span></div></div><form><div className="form-row"><label>성함·업체명<input placeholder="성함 또는 업체명" /></label><label>연락처<input placeholder="010-0000-0000" /></label></div><label>문의 분야<select><option>문의 분야를 선택하세요</option><option>기장·세무신고</option><option>창업 상담</option><option>법인 전환</option></select></label><label>문의 내용<textarea rows={6} placeholder="현재 상황과 궁금한 내용을 간단히 적어주세요" /></label><label className="consent"><input type="checkbox" /> 개인정보 수집 및 이용에 동의합니다.</label><button type="button" className="button button-primary">문의 접수하기</button><small>※ 현재 목업 화면으로, 실제 접수 기능은 연결이 필요합니다.</small></form></div></section>
  </main><SiteFooter /></>
}
